services:
  mysite:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - .:/django-tutorial
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"